name 'pihole'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures pihole'
long_description 'Installs/Configures pihole'
version '0.1.0'
chef_version '>= 13.0'

depends 'docker'
depends 'docker_base'
