---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - role[media_server.json]
    attributes:
      chef_client:
        conf_dir: "/etc/chef"
      plex:
        channel: "plexpass"
        token: "KqHuz9kXEgYAuvyQpNrf"
