name 'home_automation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Does home automation for us'
long_description 'Does home automation for us'
version '0.1.1'
chef_version '>= 13.0'

depends 'docker'
