name 'linux_base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures linux_base'
long_description 'Installs/Configures linux_base'
version '0.1.0'
chef_version '>= 13.0'

depends 'docker'
depends 'ssh_authorized_keys'
depends 'sshd'
