name 'photo_server'
maintainer 'Lucas Kjaero'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures a photo  server'
long_description 'Installs/Configures a photo server'
version '0.1.0'
chef_version '>= 13.0'

depends 'docker'
