name 'logstash_host'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures logstash_host'
long_description 'Installs/Configures logstash_host'
version '0.1.0'
chef_version '>= 14.0'

depends 'docker'
