name 'grocy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures grocy'
long_description 'Installs/Configures grocy'
version '0.1.0'
chef_version '>= 14.0'

depends 'docker'
