name: Upload cookbooks and roles to managed chef

on:
  pull_request:
    branches: [ master ]

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Set up Chef development kit
      run: |
        wget https://packages.chef.io/files/stable/chefdk/4.7.73/ubuntu/18.04/chefdk_4.7.73-1_amd64.deb
        sudo dpkg -i chefdk_4.7.73-1_amd64.deb

    - name: Upload cookbooks
      run: |
        knife upload .
